name: 🪲 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true
  - type: textarea
    id: steps
   attributes:
    label: Repro steps
    description: |
      What were you doing on the website or app when the bug happened? Detailed information helps maintainers reproduce and fix bugs.

      Issues filed without repro steps will be closed.
    placeholder: |
      Example bug report:
      1. Log in with username/password
      2. Click "Messages" on the left menu
      3. Open any message in the list
  validations:
    required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: checkboxes
    id: checks
    attributes:
      label: Extra fields
      options:
        - label: I have used the search function to check if an issue already exists
          required: true
        - label: I'd like to work on this issue
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
