name: 🚀 New Feature Report
description: Suggest or request a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        🚀 Awesome! We're excited to hear your feature suggestion. Please fill out the sections below to describe it effortlessly!
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      placeholder: E.g., Add a button in the screen X that allows to do Y
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why Should We Implement It?
      placeholder: E.g., It will allow users to do Y, which is essential for Z
  - type: textarea
    id: alternatives
    attributes:
      label: Any Alternative Ideas?
      placeholder: E.g., We could also consider doing A or B instead
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: |
        Add any other context, screenshots, or related information here.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - label: High
          value: high
        - label: Medium
          value: medium
        - label: Low
          value: low
  - type: checkboxes
    id: checks
    attributes:
      label: Extra Fields
      options:
        - label: I have used the search function to check if an issue already exists
          required: true
  - type: markdown
    attributes:
      value: |
        🚀 Thanks for your suggestion! Let's collaborate and see if we can make it happen.
