name: vitest

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx vitest
